
shallow_clone: true

environment:
  global:
    OPENCL_LIB: "C:/projects/AMD/2.9-1/bin/x86"
    OPENCL_INC: "C:/projects/AMD/2.9-1/include"
    R_BUILD_ARGS: "--no-manual --keep-empty-dirs"
    R_CHECK_ARGS: "--no-multiarch --no-build-vignettes --no-manual --no-tests"

# $ErrActionPreference = "Stop" when we tighten this up.
# DO NOT CHANGE the "init" and "install" sections below
# Download script file from GitHub
init:
  - ps: |
        $ErrorActionPreference = "Continue"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

before_build:
  - ps: cd ..
  - ps: mkdir AMD
  - ps: cd AMD
  - cmd: curl -L -o AMD.zip https://www.dropbox.com/sh/08uojexqtp364l0/AAC2rMl2MbbV9H9yCUZp3ZDqa?dl=1
  - ps: 7z x AMD.zip
  - ps: cp 2.9-1/bin/x86/OpenCL.dll C:/Windows/System32
  - ps: cp 2.9-1/bin/x86/OpenCL.dll C:/Windows/SysWOW64
  - ps: cd ..
  - ps: cd gpur

install:
  - ps: Bootstrap
  - echo Installing OpenCL
  - echo %OPENCL_LIB%
  - echo %OPENCL_INC%
  - ps: ls

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_github cdeterman/RViennaCL
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs
  
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

